
https://biobank.ndph.ox.ac.uk/showcase/coding.cgi?id=1001

https://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=21000

In [1]:
import pandas as pd
import os

In [2]:
PROJECT_PATH = "/cs/labs/michall/roeizucker/non_caucasian_run_2"
FILE_NAME = "ukbb_dataset_asthma.csv"
NEW_FILE_NAME = "african_ukbb_dataset.csv"
ETHNICITY_GROUP_NAME = "african"
TESTED_PHENOTYPES = ["I10","J45"]
# BACKROUNDS = ["3001","3002","3003","3004","5"]
BACKROUNDS = ["4002","4003","4001"]

In [3]:
file_path = os.path.join(PROJECT_PATH,FILE_NAME)
df = pd.read_csv(file_path)

In [4]:
# df

,sample_index,eid,I10,I10_F,I10_M,J45,J45_F,J45_M,Height,ehtnic_background,...,batch_UKBiLEVEAX_b10,batch_UKBiLEVEAX_b11,batch_UKBiLEVEAX_b2,batch_UKBiLEVEAX_b3,batch_UKBiLEVEAX_b4,batch_UKBiLEVEAX_b5,batch_UKBiLEVEAX_b6,batch_UKBiLEVEAX_b7,batch_UKBiLEVEAX_b8,batch_UKBiLEVEAX_b9
0,0,5895328,0.0,NaN,0.0,0.0,NaN,0.0,174.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,5764375,0.0,0.0,NaN,0.0,0.0,NaN,163.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,5503073,1.0,NaN,1.0,0.0,NaN,0.0,184.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2563626,1.0,NaN,1.0,0.0,NaN,0.0,167.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4980832,0.0,NaN,0.0,0.0,NaN,0.0,192.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400725,502513,2243883,1.0,NaN,1.0,0.0,NaN,0.0,169.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400726,502515,3570729,0.0,NaN,0.0,0.0,NaN,0.0,174.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400727,502516,1663456,0.0,NaN,0.0,0.0,NaN,0.0,165.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400728,502517,3118989,1.0,1.0,NaN,0.0,0.0,NaN,157.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400729,502519,4573284,0.0,0.0,NaN,0.0,0.0,NaN,169.0,1001.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# 3100+360

3460

In [6]:
# df["ehtnic_background_set"].where
# def filter_fn(row):
#     print("3001" in (row['ehtnic_background_set']))
#     input()
#     if row['ehtnic_background_set']:
#         return False
#     else:
#         return True

# # df = pd.DataFrame(d, columns=['Name', 'Age', 'Score'])
# m = df.apply(filter_fn, axis=1)

In [7]:
ehtnic_contained_searies = df["ehtnic_background_set"].str.contains('|'.join(BACKROUNDS)) & ~(df["ehtnic_background_set"].str.contains(","))

# ehtnic_contained_searies
# df[ehtnic_contained_searies & ~(df["ehtnic_background_set"].str.contains(","))]

In [8]:
# df[ehtnic_contained_searies]["ehtnic_background_set"].value_counts()

In [9]:
# ehtnic_contained_searies.value_counts()

In [10]:
for phen in TESTED_PHENOTYPES:
    both_sexs_col_name = phen + "_" + ETHNICITY_GROUP_NAME
    male_sexs_col_name = phen + "_M_" + ETHNICITY_GROUP_NAME
    female_sexs_col_name = phen + "_F_" + ETHNICITY_GROUP_NAME
    df[phen + "_" + ETHNICITY_GROUP_NAME] = None
    df[phen + "_M_" + ETHNICITY_GROUP_NAME] = None
    df[phen + "_F_" + ETHNICITY_GROUP_NAME] = None
#     s.str.contains('|'.join(searchfor))
    df.loc[(ehtnic_contained_searies) & (df[phen] == 1.0), f"{phen}_{ETHNICITY_GROUP_NAME}"] = 1.0
    df.loc[(ehtnic_contained_searies) & (df[phen] == 0.0), f"{phen}_{ETHNICITY_GROUP_NAME}"] = 0.0

    df.loc[(ehtnic_contained_searies) & (df[phen+"_M"] == 1.0), f"{phen}_M_{ETHNICITY_GROUP_NAME}"] = 1.0
    df.loc[(ehtnic_contained_searies) & (df[phen+"_M"] == 0.0), f"{phen}_M_{ETHNICITY_GROUP_NAME}"] = 0.0

    df.loc[(ehtnic_contained_searies) & (df[phen+"_F"] == 1.0), f"{phen}_F_{ETHNICITY_GROUP_NAME}"] = 1.0
    df.loc[(ehtnic_contained_searies) & (df[phen+"_F"] == 0.0), f"{phen}_F_{ETHNICITY_GROUP_NAME}"] = 0.0

df.to_csv(os.path.join(PROJECT_PATH,NEW_FILE_NAME))

In [11]:
print("new file:\t",os.path.join(PROJECT_PATH,phen+"_"+NEW_FILE_NAME))

new file:	 /cs/labs/michall/roeizucker/non_caucasian_run_2/J45_african_ukbb_dataset.csv