In [2]:
import pandas as pd

# remove caucasion from df

In [3]:
full_df = pd.read_csv("/cs/labs/michall/roeizucker/non_caucasian_run/ukbb_dataset.csv")
only_caucasion = pd.read_csv("/cs/labs/michall/roeizucker/non_caucasian_run/ukbb_dataset2.csv")

In [10]:
non_caucasion = full_df[~full_df.eid.isin(only_caucasion["eid"])]

In [11]:
non_caucasion.to_csv("/cs/labs/michall/roeizucker/non_caucasian_run/ukbb_dataset_non_caucasion.csv")

,sample_index,eid,F329,F329_F,F329_M,H26,H26_F,H26_M,H269,H269_F,...,batch_UKBiLEVEAX_b10,batch_UKBiLEVEAX_b11,batch_UKBiLEVEAX_b2,batch_UKBiLEVEAX_b3,batch_UKBiLEVEAX_b4,batch_UKBiLEVEAX_b5,batch_UKBiLEVEAX_b6,batch_UKBiLEVEAX_b7,batch_UKBiLEVEAX_b8,batch_UKBiLEVEAX_b9
5,5,5427659,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,11,5761858,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,13,1842631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,15,4347495,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,16,1110672,1.0,NaN,1.0,0.0,NaN,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400686,502463,5445956,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400691,502471,3226893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400709,502495,1210318,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400714,502500,3814605,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400717,502505,2031201,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0